services:
  spark-app:
    build: .
    volumes:
      - .:/app
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - PYSPARK_PYTHON=/usr/local/bin/python
    command: ["/scripts/run.sh"]
